flask-books/application/routes.py
from datetime import datetime, timedelta
import io

from sqlalchemy import extract, func, or_
from application import db
from flask import render_template, redirect, send_file, url_for, flash, request, jsonify, Blueprint
from application.models import Sale, User, Book, Review, Basket, Wishlist
from application.forms import RegisterForm, LoginForm, ReviewForm, AddBookForm, EditBookForm, AddToBasketForm, BookFilterForm, GenreForm
from flask_login import login_user, logout_user, login_required, current_user

main = Blueprint("main", __name__)
users = Blueprint("users", __name__)
books = Blueprint("books", __name__)
reviews = Blueprint("reviews", __name__)

@books.route('/books', methods=['GET', 'POST'])
def book_page():
    form = GenreForm()
    if request.method == "GET":
        if current_user.is_authenticated:
            admin_or_not = current_user.is_admin
        else:
            admin_or_not = False
        print(f'admin: {admin_or_not}')
        all_books = Book.query.all()
        return render_template('book.html', books=all_books, admin=admin_or_not, form=form)
    if request.method == "POST":
        if form.validate_on_submit():
            selected_genres = []
            price_conditions = []
            # Check each BooleanField individually
            if form.fiction.data:
                selected_genres.append('fiction')
            if form.non_fiction.data:
                selected_genres.append('non-fiction')
            if form.mystery.data:
                selected_genres.append('mystery')
            if form.science_fiction.data:
                selected_genres.append('science-fiction')
            if form.fantasy.data:
                selected_genres.append('fantasy')
            if form.romance.data:
                selected_genres.append('romance')
            if form.classic.data:
                selected_genres.append('classic')
            if form.thriller.data:
                selected_genres.append('thriller')
            if form.biography.data:
                selected_genres.append('biography')
            if form.history.data:
                selected_genres.append('history')
            if form.self_help.data:
                selected_genres.append('self-help')

            # Check each price range BooleanField
            if form.under5.data:
                price_conditions.append(Book.price < 5)
            if form.filter5_10.data:
                price_conditions.append((Book.price >= 5) & (Book.price <= 10))
            if form.filter10_15.data:
                price_conditions.append((Book.price >= 10) & (Book.price <= 15))
            if form.filter15_20.data:
                price_conditions.append((Book.price >= 15) & (Book.price <= 20))
            if form.filter20_25.data:
                price_conditions.append((Book.price >= 20) & (Book.price <= 25))

            

            print(f'Genres are: {selected_genres}')
            print(f'Price are: {price_conditions}')
            
            query = Book.query
            if selected_genres:
                query = query.filter(Book.genre.in_(selected_genres))
            # Apply the price filters if any
            if price_conditions:
                query = query.filter(or_(*price_conditions))
             # Apply the sorting preferences
            sort_option = form.sorting.data
            if sort_option == 'alphabetical':
                query = query.order_by(Book.title.asc())
            elif sort_option == 'price_low_high':
                query = query.order_by(Book.price.asc())
            elif sort_option == 'price_high_low':
                query = query.order_by(Book.price.desc())
            all_books = query.all()
        else:
            all_books = Book.query.all()

        return render_template('book.html', books=all_books, form=form)

@books.route('/books/<id>', methods=['GET', 'POST'])
def home_page(id):
    form = ReviewForm()
    form2 = AddToBasketForm()
    if request.method == "GET":
        if current_user.is_authenticated:
            admin_or_not = current_user.is_admin
        else:
            admin_or_not = False
        
        book = Book.query.filter_by(id=id).first()
        book_review = Review.query.filter_by(book_id=id).all()

        # Calculate average review rating
        average_rating = 0.0
        total_reviews = len(book_review)

        if total_reviews > 0:
            for review in book_review:
                average_rating += review.rating

            average_rating /= total_reviews

        similar_books = Book.query.filter_by(genre=book.genre).all()
        
        return render_template('individual-book.html', book=book, reviews=book_review, similar_books=similar_books, average_rating=average_rating, form=form, form2=form2, admin=admin_or_not)
    
    if request.method == "POST":
        form_type = request.form.get('form_type')
        current_id = current_user.id
        if form_type == 'add_review':
        
            selected_rating = request.form['rate']
            
            
            if form.validate_on_submit():            
                review_to_create = Review(book_id=id, user_id=current_id, review_text=form.review.data, rating=selected_rating)
                db.session.add(review_to_create)
                db.session.commit()
                flash(f"Review created successfully!", category="success")
            else:
                # Print form errors to identify the issue
                print(form.errors)

                for field, errors in form.errors.items():
                    for error in errors:
                        flash(f'There was an error with the field "{field}": {error}', category='danger')

            # Retrieve the book and reviews again after the new review is added
            book = Book.query.filter_by(id=id).first()
            book_review = Review.query.filter_by(book_id=id).all()

            # Calculate average review rating
            average_rating = 0.0
            total_reviews = len(book_review)

            if total_reviews > 0:
                for review in book_review:
                    average_rating += review.rating

                average_rating /= total_reviews

            similar_books = Book.query.filter_by(genre=book.genre).all()

            return render_template('individual-book.html', book=book, reviews=book_review, similar_books=similar_books, average_rating=average_rating, form=form, form2=form2)
        elif request.form['action'] == 'add_to_basket':
            book_quantity = form2.quantity.data
            if book_quantity > 0:
                Basket.add_to_basket(user_id=current_id, book_id=id,quantity=book_quantity)
                flash(f'{book_quantity} items added to basket', category='warning')
                return redirect(url_for('main.basket_page'))
            else:
                flash(f'quantity has to be greater than {book_quantity}', category='danger')

                # Retrieve the book again
                book = Book.query.filter_by(id=id).first()
                book_review = Review.query.filter_by(book_id=id).all()

                # Calculate average review rating
                average_rating = 0.0
                total_reviews = len(book_review)

                if total_reviews > 0:
                    for review in book_review:
                        average_rating += review.rating

                    average_rating /= total_reviews

                similar_books = Book.query.filter_by(genre=book.genre).all()

                return render_template('individual-book.html', book=book, reviews=book_review, similar_books=similar_books, average_rating=average_rating, form=form,form2=form2)
        elif request.form['action'] == 'add_to_wishlist':
            book_quantity = form2.quantity.data
            if book_quantity > 0:
                Wishlist.add_to_wishlist(user_id=current_id, book_id=id,quantity=book_quantity)
                flash(f'{book_quantity} items added to wishlist', category='warning')
                return redirect(url_for('main.wishlist_page'))
            else:
                flash(f'quantity has to be greater than {book_quantity}', category='danger')

                # Retrieve the book again
                book = Book.query.filter_by(id=id).first()
                book_review = Review.query.filter_by(book_id=id).all()

                # Calculate average review rating
                average_rating = 0.0
                total_reviews = len(book_review)

                if total_reviews > 0:
                    for review in book_review:
                        average_rating += review.rating

                    average_rating /= total_reviews

                similar_books = Book.query.filter_by(genre=book.genre).all()

                return render_template('individual-book.html', book=book, reviews=book_review, similar_books=similar_books, average_rating=average_rating, form=form,form2=form2)

@books.route('/search', methods=['GET','POST'])
def search_books():
    if current_user.is_authenticated:
        admin_or_not = current_user.is_admin
    else:
        admin_or_not = False
    query = request.form.get('search')
    similar_books_by_title = Book.query.filter(Book.title.ilike(f'%{query}%')).all()
    similar_books_by_author = Book.query.filter(Book.author.ilike(f'%{query}%')).all()

    return render_template(
        'search_results.html',
        query=query,
        books_by_title=similar_books_by_title,
        books_by_author=similar_books_by_author,
        admin=admin_or_not
    )

@main.route('/register', methods=['GET','POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():

flask-books/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="../static/book.css" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav first-nav">
          <li>
            <a class="navbar-brand" href="{{ url_for('main.main_page') }}">
              <img
                src="../static/assets/wmgzon-logo.png"
                width="90"
                height="30"
                alt=""
              />
            </a>
          </li>
          <li>
            <form
              class="form-inline my-2 my-lg-0"
              action="{{ url_for('books.search_books') }}"
              method="POST"
            >
              <input
                class="form-control mr-sm-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
                name="search"
              />
              <button
                class="btn btn-outline-success my-2 my-sm-0"
                type="submit"
              >
                Search
              </button>
            </form>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.login_page') }}"
              >Account Info<span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div
        class="collapse navbar-collapse second-nav"
        id="navbarSupportedContent"
      >
        <ul class="navbar-nav second-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Fashion<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home & Garden<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a
              class="nav-link font-weight-bold"
              href="{{ url_for('books.book_page') }}"
              >Books<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Toys & Games<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Electronics<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Music<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Other<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a
              class="nav-link font-weight-bold"
              href="{{ url_for('main.wishlist_page')}}"
              >Wishlist<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a
              class="nav-link font-weight-bold"
              href="{{ url_for('main.basket_page')}}"
              >Basket<span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
      </div>
    </nav>
    {% if admin %}
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav second-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >You Are Logged In As An Admin<span class="sr-only"
                >(current)</span
              ></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.admin_page') }}"
              >View Product Database<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.statistics_page') }}"
              >View Statistical Analysis<span class="sr-only"
                >(current)</span
              ></a
            >
          </li>
        </ul>
      </div>
    </nav>
    {% endif %} {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      <button
        type="button"
        class="m1-2 mb-1 close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

flask-books/application/templates/basket.html
{% extends 'base.html' %} {% block title %} Basket {% endblock %} {% block
content %} {% if items %}
<div id="basket">
  
  <div id="all-items-container">
    <h1>Basket</h1>
    {% for item in items%}
    <div id="individual-item-container">
      <div id="book-part">
        <div id="individual-basket-img">
          <a href="{{ url_for('books.home_page', id=item.book.id) }}">
            <img
              class="book-img"
              src="{{ url_for('books.display', book_id=item.book.id) }}"
              alt="Book Image"
            />
          </a>
        </div>
        <div class="basket-item-desc">
          <p>{{item.book.title}}<br />£{{item.book.price}}</p>
        </div>
        <div id="quantity-part">
          <form method="POST" action="{{ url_for('main.update_basket') }}">
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <label for="quantity">Quantity:</label>
            <select name="quantity" onchange="this.form.submit()">
              {% for i in range(1, 11) %}
                <option value="{{ i }}" {% if i == item.quantity %}selected{% endif %}>{{ i }}</option>
              {% endfor %}
            </select>
          </form>
        </div>
        <div>
          <form method="POST" action="{{ url_for('main.basket_page') }}">
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <button
              type="submit"
              name="action"
              value="delete"
              class="remove-btn"
            >
              Remove Item
            </button>
          </form>
          <form method="POST" action="{{ url_for('main.basket_page') }}">
            <input type="hidden" name="action" value="move_to_wishlist">
            <input type="hidden" name="book_id" value="{{ item.book.id }}" />
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <button
              type="submit"
              class="wishlist-btn"
            >
              Add to Wishlist
            </button>
          </form>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
  <div id="basket-summary">
    <h1>
      subtotal: <br />
      £{{subtotal}}
    </h1>
    <div id="Continue-shopping-div">
      <h3>Continue Shopping</h3>
      <form method="POST" action="{{ url_for('main.basket_page') }}">
        <input type="hidden" name="action" value="checkout">
        <button type="submit" id="checkout-btn">Checkout</button>
      </form>
    </div>
  </div>
</div>
{% else %}
<h1 id="no-basket-msg">
  No items in basket!<br />
  Visit <a href="{{ url_for('books.book_page')}}">here</a> to see our books!
</h1>
{% endif %} {% endblock %}

flask-books/application/templates/book.html
{% extends 'base.html' %} {% block title %} Books {% endblock %} {% block
content %}
<div id="main-div">
  <div id="filters-div">
    <h1>Listing Preferences</h1>
    <form method="POST" action="{{ url_for('books.book_page') }}">
    <div id="filters">
      <a
        class="btn btn-primary filter-btn"
        data-toggle="collapse"
        href="#collapseGenres"
        role="button"
        aria-expanded="false"
        aria-controls="collapseGenres"
      >
        Genres
      </a>
      <div class="collapse" id="collapseGenres">
        
          {{ form.hidden_tag() }} {{ form.fiction.label }} {{ form.fiction }}<br />
          {{ form.non_fiction.label }} {{ form.non_fiction }}<br />
          {{ form.mystery.label }} {{ form.mystery }}<br />
          {{ form.science_fiction.label }} {{ form.science_fiction }}<br />
          {{ form.fantasy.label }} {{ form.fantasy }}<br />
          {{ form.romance.label }} {{ form.romance }}<br />
          {{ form.classic.label }} {{ form.classic }}<br />
          {{ form.thriller.label }} {{ form.thriller }}<br />
          {{ form.biography.label }} {{ form.biography }}<br />
          {{ form.history.label }} {{ form.history }}<br />
          {{ form.self_help.label }} {{ form.self_help }}<br />

      </div>
      <a
        class="btn btn-primary filter-btn"
        data-toggle="collapse"
        href="#collapsePrices"
        role="button"
        aria-expanded="false"
        aria-controls="collapsePrices"
      >
        Price
      </a>
      <div class="collapse" id="collapsePrices">
        <!-- Price range options -->
          {{ form.under5.label }} {{ form.under5 }}<br />
          {{ form.filter5_10.label }} {{ form.filter5_10 }}<br />
          {{ form.filter10_15.label }} {{ form.filter10_15 }}<br />
          {{ form.filter15_20.label }} {{ form.filter15_20 }}<br />
          {{ form.filter20_25.label }} {{ form.filter20_25 }}<br />
      </div>
      <a
        class="btn btn-primary filter-btn"
        data-toggle="collapse"
        href="#collapseSort"
        role="button"
        aria-expanded="false"
        aria-controls="collapseSort"
      >
        Sort
      </a>
      <div class="collapse" id="collapseSort">
        <!-- Sorting options -->
        {% for option in form.sorting %}
        {{ option }} {{ option.label }}<br />
        {% endfor %}
      </div>
      {{ form.submit(class="btn btn-primary filter-btn", id="apply-filter") }}
    </form>
    </div>
  </div>
  <div id="my-container">
    {% for book in books %}
    {% if not book.delisted %}
    <div class="book-div">
      <a href="{{ url_for('books.home_page', id=book.id) }}">
        <div class="item-font">
          {% if book.book_picture %}
          <img
            class="book-img"
            src="{{ url_for('books.display', book_id=book.id) }}"
            alt="Book Image"
          />

          {% endif %}
          <p class="font-margin">{{ book.title }}</p>
          <p>£{{ book.price }}</p>
        </div>
      </a>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

flask-books/application/templates/login.html
{% extends 'base.html' %} {% block title %} Login Page {% endblock %} {% block
content %}

<div class="container">
  <form method="POST" class="form-signin" style="color: white">
    {{ form.hidden_tag() }}
    <img class="mb-4" src="../static/assets/wmgzon-logo.png" alt="" />
    <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
    <br />
    {{ form.email_address.label() }} {{ form.email_address(class="form-control",
    placeholder="Email Address") }} {{ form.password.label() }} {{
    form.password(class="form-control", placeholder="Password") }}

    <br />

    <div class="checkbox mb-3">
      <h6 class="register-text">Do not have an account?</h6>
      <a
        class="btn btn-sm btn-secondary"
        href="{{ url_for('main.register_page') }}"
        >Register</a
      >
    </div>

    {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
  </form>
</div>

{% endblock %}

flask-books/application/templates/main-page.html
{% extends 'base.html' %} {% block title %} Main Page {% endblock %} {% block
content %}
<div id="sale-container">
  <img
    src="../static/assets/big-sale-image.png"
    alt="The big sale image"
    class="big-sale-img"
  />

  <div id="smaller-sale-container">
    <div id="christmas" class="sale">
      <img
        src="../static/assets/shop-valentines.png"
        alt="Valentines image"
        class="valentines-img"
      />
      <button class="valentines-btn">Shop Valentines</button>
    </div>
    <div id="clearance" class="sale">
      <img
        src="../static/assets/Clearance.PNG"
        alt="Clearance image"
        class="clearance-image"
      />
      <button class="clearance-btn">Shop Clearance</button>
    </div>
    <div id="sale" class="sale">
      <img
        src="../static/assets/shop-book 2.jpg"
        alt="Book image"
        class="main-book-img"
      />
      <a class="shop-books-btn" href="{{ url_for('books.book_page') }}">
        Shop Book
      </a>
    </div>
  </div>
</div>
{% endblock %}

flask-books/application/templates/register.html
{% extends 'base.html' %} {% block title %} Register Page {% endblock %} {%
block content %}

<div class="container">
  <form method="POST" class="form-register" style="color: white">
    {{ form.hidden_tag() }}
    <img class="mb-4" src="../static/assets/wmgzon-logo.png" alt="" />
    <h1 class="h3 mb-3 font-weight-normal">Please Create your Account</h1>
    <br />
    {{ form.email_address.label() }} {{ form.email_address(class="form-control",
    placeholder="Email Address") }} {{ form.password1.label() }} {{
    form.password1(class="form-control", placeholder="Password") }} {{
    form.password2.label() }} {{ form.password2(class="form-control",
    placeholder="Confirm Password") }}

    <br />

    <div class="checkbox mb-3">
      <h6 class="register-text">Already have an account?</h6>
      <a
        class="btn btn-sm btn-secondary"
        href="{{ url_for('main.login_page') }}"
        >Login</a
      >
    </div>

    {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
  </form>
</div>

{% endblock %}

flask-books/application/templates/search_results.html
{% extends 'base.html' %} {% block title %} Books {% endblock %} {% block
content %}
<h2>Search Results for "{{ query }}"</h2>

{% if books_by_title or books_by_author %}
<h3>By Title:</h3>
{% if books_by_title %}
<div id="my-container">
  {% for book in books_by_title %}
  <div class="book-div">
    <a href="{{ url_for('books.home_page', id=book.id) }}">
      <div class="item-font">
        {% if book.book_picture %}
        <img
          class="book-img"
          src="{{ url_for('books.display', book_id=book.id) }}"
          alt="Book Image"
        />

        {% endif %}
        <p class="font-margin">{{ book.title }}</p>
        <p>£{{ book.price }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No books found by title for "{{ query }}".</p>
{% endif %}

<h3>By Author:</h3>
{% if books_by_author %}
<div id="my-container">
  {% for book in books_by_author %}
  <div class="book-div">
    <a href="{{ url_for('books.home_page', id=book.id) }}">
      <div class="item-font">
        {% if book.book_picture %}
        <img
          class="book-img"
          src="{{ url_for('books.display', book_id=book.id) }}"
          alt="Book Image"
        />

        {% endif %}
        <p class="font-margin">{{ book.title }}</p>
        <p>£{{ book.price }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No books found by author for "{{ query }}".</p>
{% endif %} {% else %}
<p>No books found for "{{ query }}".</p>
{% endif %} {% endblock %}

flask-books/application/templates/wishlist.html
{% extends 'base.html' %} {% block title %} Wishlist {% endblock %} {% block
content %} {% if items %}
<div id="basket">
  
  <div id="all-items-container">
    <h1>Wishlist</h1>
    {% for item in items%}
    <div id="individual-item-container">
      <div id="book-part">
        <div id="individual-basket-img">
          <a href="{{ url_for('books.home_page', id=item.book.id) }}">
            <img
              class="book-img"
              src="{{ url_for('books.display', book_id=item.book.id) }}"
              alt="Book Image"
            />
          </a>
        </div>
        <div class="basket-item-desc">
          <p>{{item.book.title}}<br />£{{item.book.price}}</p>
        </div>
        <div id="quantity-part">
          <form method="POST" action="{{ url_for('main.update_wishlist') }}">
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <label for="quantity">Quantity:</label>
            <select name="quantity" onchange="this.form.submit()">
              {% for i in range(1, 11) %}
                <option value="{{ i }}" {% if i == item.quantity %}selected{% endif %}>{{ i }}</option>
              {% endfor %}
            </select>
          </form>
        </div>
        <div>
          <form method="POST" action="{{ url_for('main.wishlist_page') }}">
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <button
              type="submit"
              name="action"
              value="delete"
              class="remove-btn"
            >
              Remove Item
            </button>
          </form>
          <form method="POST" action="{{ url_for('main.wishlist_page') }}">
            <input type="hidden" name="action" value="move_to_wishlist">
            <input type="hidden" name="book_id" value="{{ item.book.id }}" />
            <input type="hidden" name="basket_id" value="{{ item.id }}" />
            <button
              type="submit"
              class="move-to-basket-btn"
            >
              Add to Basket
            </button>
          </form>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
  <div id="basket-summary">
    
    <div id="Continue-shopping-div">
      <h3>Continue Shopping</h3>
      <a href="{{ url_for('main.basket_page')}}"><h3>Go to Basket</h3></a>
    </div>
  </div>
</div>
{% else %}
<h1 id="no-basket-msg">
  No items in wishlist!<br />
  Visit <a href="{{ url_for('books.book_page')}}">here</a> to see our books!
</h1>
{% endif %} {% endblock %}